name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          cp target/*.jar staging
      - name: uploud
        uses: actions/uploud-artifact@v2
        with:
          name: github-actions-artifact
          path: target
